### ISSUE TITLE
Special characters in captions [request]

### ISSUE THREAD

**Issue by stineb** [adletaw/captioner#37] opened 2018-09-20 07:28 UTC
Is there a way to use special characters in captions (e.g., superscripts, lowerscripts, greek letters, math symbols, etc.)? From my experience with captioner `expression()` or `bquote()` don't work.

**Comment by GegznaV** [comment] 2018-09-20 08:28
In R strings you should use double slashes: if you mean `\`, write `\\`, e.g., `"$\\alpha$"`, `"$\\sum^n_{i=2}(x_i+2)$"`. Do these equations work?

**Comment by stineb** [comment] 2018-09-20 08:34
Yes, this works. Great. Workaround using latex (`$`) instead of `expression()` or `bquote()`, then...

**Comment by GegznaV** [comment] 2018-09-20 12:11
@stineb, if the issue is solved, consider closing it.

**Closed** 2018-09-21 06:26 UTC
